import type { Metadata } from 'next'
import './globals.css'
import { Cinzel_Decorative, Tangerine, Cormorant } from 'next/font/google'

import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import { InfoPlate } from '@/components/info-plate'

const cinzelDecorative = Cinzel_Decorative({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
})

const tangerine = Tangerine({
  weight: ['400', '700'],
  subsets: ['latin'],
})

const cormorant = Cormorant({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzelDecorative.className} ${tangerine.className} ${cormorant.className}`}
      >
        <Header />
        <InfoPlate />
        {children}
        <Footer />
      </body>
    </html>
  )
}
