import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Link href={"/"}>Home</Link>
          <Link href={"/shop-products"}>Shop Products</Link>
          <Link href={"/about-us"}>About Us</Link>
          <Link href={"/book-appointment"}>Book Appointment</Link>
          <Link href={"/info"}>Info</Link>
          <Link href={"/spa-services"}>Spa Services</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
