name: Main
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
      - run: yarn install --frozen-lockfile --check-files --silent
      - run: yarn lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile --check-files --silent
      - run: yarn test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-report
          path: jest-report/
          retention-days: 10

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile --check-files --silent
      - run: npx playwright install --with-deps
      - run: yarn e2e-ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
