name: Update Dogs Data

on:
  schedule:
    - cron: '0 0 * * 1'  # запускать каждую неделю в понедельник в полночь UTC
  workflow_dispatch:

jobs:
  update-production:
    runs-on: ubuntu-latest
    steps:
      - name: Call updateDogs for Production
        run: |
          curl -X GET https://doggy-spa-one.vercel.app/api/updateDogs
